const data = {
  products: [
    {
      _id: '1',
      name: 'Silky Embroidered Tank',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 35,
      countInStock: 10,
      brand: 'Forever 21',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Black Tank Top',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 20,
      countInStock: 20,
      brand: 'H & M',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Black Lace Blouse',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 30,
      countInStock: 0,
      brand: 'Guess',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Embroidedred Womens Top',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 45,
      countInStock: 15,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'White Lace Layered Tee',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 30,
      countInStock: 5,
      brand: 'Banana Republic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Simple Red T-Shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 15,
      countInStock: 12,
      brand: 'H & M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
